---
- name: Deploy Flask App
  hosts: servers
  become: true

  tasks:
    - name: Ensure git is installed
      ansible.builtin.apt:
        name: git
        state: present

    - name: Clone or update the application repository
      ansible.builtin.git:
        repo: 'https://github.com/skardiz/simple-flask-app.git'
        dest: /root/simple-flask-app
        version: main
        force: yes

    - name: Deploy application with Docker Compose
      ansible.builtin.command:
        cmd: docker compose up -d --pull always
        chdir: /root/simple-flask-app
